/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginandsignup;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static loginandsignup.Login.userModel;
import models.UserModel;

/**
 *
 * @author user
 */
public class User extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    final String EMPCODE = "PSS00";

    /**
     * Creates new form User
     */
    public User() {
        conn = db.java_db();
        initComponents();
        getDBData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_aadhar = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_doj = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_designation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_department = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_account = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_pancard = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_father = new javax.swing.JTextField();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("NUMBER OF PROJECTS");

        jLabel21.setText("jLabel21");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("       Welcome,User Panel");

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/icons8_Tick_Box_35px_1.png"))); // NOI18N
        jButton4.setText("Attendence");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/icons8_Info_35px.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 650));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCalendar1.setBackground(new java.awt.Color(0, 102, 102));
        jCalendar1.setForeground(new java.awt.Color(0, 102, 102));
        jCalendar1.setDecorationBackgroundColor(new java.awt.Color(0, 102, 102));
        jCalendar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCalendar1.setWeekdayForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 250, 190));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Name");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("DOB");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 50, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Gender");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        txt_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel4.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 30));

        txt_dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dobActionPerformed(evt);
            }
        });
        jPanel4.add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 200, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Contact No");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Address");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Account No");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Department");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        txt_contact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 200, 30));

        txt_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 200, 30));

        txt_aadhar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txt_aadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 200, 30));

        txt_salary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txt_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 180, 30));

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 120));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Designation");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        txt_doj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txt_doj, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 180, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Salary");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, -1));

        txt_designation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txt_designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 180, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Aadhar No");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        txt_department.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txt_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 180, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Date of Hire");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        txt_account.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txt_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 180, 30));

        jButton2.setText("Update");
        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 140, 50));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setText("Email");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));
        jPanel4.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 180, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setText("PanCard No");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));
        jPanel4.add(txt_pancard, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 180, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setText("Emp ID");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel4.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel25.setText("Father Name");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));
        jPanel4.add(txt_father, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 476, 200, 30));

        r_male.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        jPanel4.add(r_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        r_female.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        jPanel4.add(r_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pen (1).jpg"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pen (1).jpg"))); // NOI18N
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 930, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        myAttendence myAttendence = new myAttendence();
        myAttendence.setVisible(true);
        myAttendence.pack();
        myAttendence.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int a = JOptionPane.showConfirmDialog(this, "Do you want to logout now", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            Login LoginFrame = new Login();
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

     
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to Update record?", "Update Record", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            try {

                String query = "update employee_information set Telephone=?,Address=?,Department=?,Designation =?";
                pst = conn.prepareStatement(query);
                pst.setString(1, txt_contact.getText());
                pst.setString(2, txt_address.getText());
                
                pst.execute();

                JOptionPane.showMessageDialog(null, "Record Updated");
                
            } catch (Exception e) {
                Logger.getLogger(Emp_Detail.class.getName()).log(Level.SEVERE, null, e);
                JOptionPane.showMessageDialog(null, e);

            } finally {

                try {

                    //pst.close();
                } catch (Exception e) {
                    Logger.getLogger(Emp_Detail.class.getName()).log(Level.SEVERE, null, e);
                }
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dobActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        gender = "Male";
        r_male.setSelected(true);
        r_female.setSelected(false);
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        gender = "Female";
        r_male.setSelected(false);
        r_female.setSelected(true);
    }//GEN-LAST:event_r_femaleActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField txt_aadhar;
    private javax.swing.JTextField txt_account;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_father;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pancard;
    private javax.swing.JTextField txt_salary;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;

    File selectedFile = null;

    private String gender;

    private void fetchEmpData() {

        System.out.println("loginandsignup.Emp_Detail.txt_searchActionPerformed()");
        String sql = "select * from employee_information where id=? ";

        try {
            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();

            if (rs.next()) {

                String add1 = rs.getString("id");
                txt_id.setText(EMPCODE + add1);

                String add2 = rs.getString("first_name");
                txt_name.setText(add2);

                String add3 = rs.getString("Dob");
                txt_dob.setText(add3);

                String add5 = rs.getString("Email");
                txt_email.setText(add5);

                String add6 = rs.getString("Telephone");
                txt_contact.setText(add6);

                String add7 = rs.getString("Fathername");
                txt_father.setText(add7);

                String add8 = rs.getString("account");
                txt_account.setText(add8);

                String add9 = rs.getString("Address");
                txt_address.setText(add9);

                String add10 = rs.getString("Department");
                txt_department.setText(add10);

                String add11 = rs.getString("Designation");
                txt_designation.setText(add11);

                String add12 = rs.getString("Salary");
                txt_salary.setText(add12);

                String add13 = rs.getString("Aadhar_no");
                txt_aadhar.setText(add13);

                String add14 = rs.getString("Date_hired");
                txt_doj.setText(add14);

                String add16 = rs.getString("Pancard_no");
                txt_pancard.setText(add16);

                gender = rs.getString("Gender");
                r_male.setSelected(false);
                r_female.setSelected(false);
                if (gender.equals("Male")) {
                    r_male.setSelected(true);
                } else {
                    r_female.setSelected(true);
                }

                byte[] image = rs.getBytes("Image");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH));
                img.setIcon(imageIcon);

                try {
                    selectedFile = File.createTempFile("tempImage", ".jpg");
                    FileOutputStream fos = new FileOutputStream(selectedFile);
                    fos.write(image);
                    fos.close();
                } catch (IOException ex) {
                    Logger.getLogger(Emp_Detail.class.getName()).log(Level.SEVERE, null, ex);
                }
                // Write the image bytes to the temporary file
            } else {
                System.out.println("Data not Found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Emp_Detail.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

            try {

                pst.close();

            } catch (Exception e) {

            }
        }
    }

    private void getDBData() {
        try {
            String query = "SELECT * From employee_information WHERE id='" + Login.userModel.id + "'";
            System.out.println(query);
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(new JFrame(), "Incorrect email or password", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                int id = rs.getInt("id");
                String first_name = rs.getString("first_name");
                String surname = rs.getString("surname");
                String Dob = rs.getString("Dob");
                String Email = rs.getString("Email");
                String Contect = rs.getString("Telephone");
                String Fathername = rs.getString("Fathername");
                String Address = rs.getString("Address");
                String account = rs.getString("account");
                String Department = rs.getString("Department");
                String Designation = rs.getString("Designation");
                String Salary = rs.getString("Salary");
                String AadharNo = rs.getString("Aadhar_no");
                String Date_hired = rs.getString("Date_hired");
                String Pancard = rs.getString("Pancard_no");
                String Gender = rs.getString("Gender");

                txt_id.setText("" + id);
                txt_name.setText(first_name + " " + surname);
                txt_dob.setText(Dob);
                txt_email.setText(Email);
                txt_contact.setText(Contect);
                txt_father.setText(Fathername);
                txt_address.setText(Address);
                txt_account.setText(account);
                txt_department.setText(Department);
                txt_designation.setText(Designation);
                txt_aadhar.setText(AadharNo);
                txt_doj.setText(Date_hired);
                txt_pancard.setText(Pancard);
                txt_salary.setText(Salary);

                txt_id.setEditable(false);
                txt_name.setEditable(false);
                txt_dob.setEditable(false);
                txt_email.setEditable(false);
                txt_father.setEditable(false);
                txt_account.setEditable(false);
                txt_aadhar.setEditable(false);
                txt_doj.setEditable(false);
                txt_pancard.setEditable(false);
                txt_salary.setEditable(false);
                txt_department.setEditable(false);
                txt_designation.setEditable(false);

                if (Gender.equals("Female")) {
                    r_female.setSelected(true);
                    r_male.setSelected(false);
                } else {
                    r_male.setSelected(true);
                    r_female.setSelected(false);
                }
                byte[] image = rs.getBytes("Image");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH));
                img.setIcon(imageIcon);

                try {
                    selectedFile = File.createTempFile("tempImage", ".jpg");
                    FileOutputStream fos = new FileOutputStream(selectedFile);
                    fos.write(image);
                    fos.close();
                } catch (IOException ex) {
                    Logger.getLogger(Emp_Detail.class.getName()).log(Level.SEVERE, null, ex);
                }
                // Write the image bytes to the temporary file
            }
        } catch (SQLException ex) {
            Logger.getLogger(Emp_Detail.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

            try {

                pst.close();

            } catch (Exception e) {

            }

        }
    }

}
